name: Build and SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    environment: SONAR_TOKEN
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run tests and generate coverage
        run: |
          npm test -- --coverage
          npx nyc report --reporter=lcov

      - name: List files in .nyc_output
        run: ls -la .nyc_output

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-scan-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=MathieuAudibert_BlockChain
            -Dsonar.organization=mathieuaudibert
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.javascript.lcov.reportPaths=.nyc_output/lcov.info
            -Dsonar.coverage.exclusions=**/test/**,**/mock/**
