name: Build and SonarCloud Analysis
on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Firebase credentials
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_CREDENTIALS }}
        working-directory: backend
        run: |
          mkdir -p bdd
          echo "$FIREBASE_KEY" > bdd/cle.json
          ls -la bdd/cle.json

      - name: Run tests with coverage
        working-directory: backend
        run: |
          python -m pytest test/unit.py --cov=. --cov-report=xml:coverage.xml --junitxml=test-results.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=MathieuAudibert_Cooloc
            -Dsonar.organization=mathieuaudibert
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=backend
            -Dsonar.tests=backend/test
            -Dsonar.python.coverage.reportPaths=backend/coverage.xml
            -Dsonar.python.xunit.reportPath=backend/test-results.xml
            -Dsonar.coverage.exclusions=**/test/**,**/__pycache__/**
